[package]
name = "p2p_instant_messenger"
version = "0.1.0"
edition = "2021"

[dependencies]
tui = "0.17"
crossterm = "0.22"
unicode-width = "0.1.5"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
